apiVersion: v1
kind: Service
metadata:
  name: hextris-service
spec:
  type: NodePort
  selector:
    app: hextris
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30100
